name: Zip repo to opencart extension type
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/v}
    - name: Bumb the version
      run: |
        sed -i -e "s@\(<version>\).*\(<\/version>\)@\1${{ steps.get_version.outputs.VERSION }}\2@" install.xml
    - name: Opencart extension zip
      uses: thedoctor0/zip-release@master
      with:
        filename: 'knawat-dropshipping-opencart.ocmod.zip'
        exclusions: '*.git* .gitignore'
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}.ocmod.zip
        asset_name: ${{ github.event.repository.name }}-${{ steps.get_version.outputs.VERSION }}.ocmod.zip
        asset_content_type: application/zip
